import { QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import ReactDOM from "react-dom/client";

import Loader from "./components/loader";
import { routeTree } from "./routeTree.gen";
import { orpc, queryClient } from "./utils/orpc";

// Browser entry point.
//
// ./routeTree.gen is generated by @tanstack/router-plugin during `vp dev` / `vp build`, so it
// is gitignored and must not be created by hand. Adding a file under src/routes is enough to
// register a new screen; the plugin regenerates the tree and the route id must match the
// filesystem path (see createFileRoute("/_app/alumni/$id") in src/routes/_app/alumni/$id.tsx).
//
// TODO(PLAKY-WEB): PLAKY-WEB-001 - keep the router options below unchanged: intent
// preloading, scroll restoration, and the pending component are part of the UX contract
// described in docs/system/user-guide.md.
const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  scrollRestoration: true,
  defaultPendingComponent: () => <Loader />,
  context: { orpc, queryClient },
  Wrap: function WrapComponent({ children }: { children: React.ReactNode }) {
    return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>;
  },
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById("app");

if (!rootElement) {
  throw new Error("Root element not found");
}

if (!rootElement.innerHTML) {
  const root = ReactDOM.createRoot(rootElement);
  root.render(<RouterProvider router={router} />);
}